auto:
  offset:
    reset: largest

groupid: 'kafka-swoole'

socket:
  timeout:
    ms: 30000 # socket超时时间
  buffersize: 64 * 1024 # socket receive buffer

fetch:
  size: 300 * 1024 # 控制在一个请求中获取的消息的字节数。 这个参数在0.8.x中由fetch.message.max.bytes,fetch.min.bytes取代
