# a string that uniquely identifies a set of consumers within the same consumer group
group.id: "kafka-swoole"

# the socket timeout for network requests. Its value should be at least fetch.wait.max.ms.
socket.timeout.ms: 30 * 1000

# the socket receive buffer for network requests
socket.receive.buffer.bytes: 64 * 1024

# the number of bytes of messages to attempt to fetch
fetch.message.max.bytes: 1024 * 1024

# the number process used to fetch data
num.consumer.fetchers: 1

# if true, periodically commit to zookeeper the offset of messages already fetched by the consumer
auto.commit.enable: true

# the frequency in ms that the consumer offsets are committed to zookeeper
auto.commit.interval.ms: 60 * 1000

# max number of message chunks buffered for consumption, each chunk can be up to fetch.message.max.bytes
queued.max.message.chunks: 2

# max number of retries during rebalance
rebalance.max.retries: 4

# what to do if an offset is out of range.
# smallest : automatically reset the offset to the smallest offset
# largest : automatically reset the offset to the largest offset
# anything else: throw exception to the consumer
auto.offset.reset: largest

# Select a strategy for assigning partitions to consumer streams. Possible values: range, roundrobin
partition.assignment.strategy: range