# this parameter specifies whether the messages are sent asynchronously
# or not. Valid values are - async for asynchronous send
#                            sync for synchronous send
producer.type: sync

# The leader may be unavailable transiently, which can fail the sending of a message.
# This property specifies the number of retries when such failures occur.
message.send.max.retries: 3

# Before each retry, the producer refreshes the metadata of relevant topics. Since leader
# election takes a bit of time, this property specifies the amount of time that the producer
# waits before refreshing the metadata.
retry.backoff.ms: 100